.circleci/config.yml
.gitignore
docs/source/conf.py

feat: added job which checks if code is formatted correctly in CircleCi, code formatted using black

add code formatting

---

docs/configuration.md

Added description of a new config change

added description to config changes

---

docs/configuration.md
docs/gettingstarted/sc4snmp-installation.md
docs/gettingstarted/sck-installation.md
docs/gettingstarted/splunk-requirements.md

changes to documentation when testing installation process

docummentation corrections

---

deploy-helm/snmp-installer/templates/sc4snmp/internal/mib-server-deployment.yaml
deploy-helm/snmp-installer/templates/sc4snmp/internal/scheduler-deployment.yaml
deploy-helm/snmp-installer/templates/sc4snmp/internal/traps-deployment.yaml
deploy-helm/snmp-installer/templates/sc4snmp/internal/worker-deployment.yaml

Builds paths changed to end with /container - made those changed to helm build so it will work

correct path to builds

---

charts/templates/mib/mib-server-deployment.yaml
charts/templates/poller/scheduler-config.yaml
charts/templates/poller/scheduler-deployment.yaml
charts/templates/poller/worker-deployment.yaml
test/README_ENV_SETUP

Allow use of Mongo with replica set by using the uri connection syntax

feat!: Use Mongo URI syntax

---

charts/templates/otel/otel-deployment.yaml
charts/values.yaml.example

Update the otel image and make the registry and tags configruable

fix: Update Otel to 0.37.1 and deployment

---

poetry.lock
pyproject.toml
splunk_connect_for_snmp/celery_config.py
splunk_connect_for_snmp/enrich/tasks.py
splunk_connect_for_snmp/inventory/tasks.py
splunk_connect_for_snmp/poller.py
splunk_connect_for_snmp/snmp/tasks.py
splunk_connect_for_snmp/splunk/tasks.py

This PR replaces send_task with canvas so the beat scheduler can drive tasks as a workflow

feat: Use canvas syntax for schedules

---

.gitignore
config.yaml.example
pyproject.toml
splunk_connect_for_snmp/inventory/tasks.py
splunk_connect_for_snmp/profiles/base.yaml
splunk_connect_for_snmp/profiles/mikrotik.yaml

* This change allows for multiple oob profile "files" with related content such as base and vendor
* Allow users to disable and override profiles via config

fix: Improve profile config system

---

.gitignore
charts/splunk-connect-for-snmp/Chart.lock
charts/splunk-connect-for-snmp/Chart.yaml
charts/splunk-connect-for-snmp/templates/inventory/_helpers.tpl
charts/splunk-connect-for-snmp/templates/inventory/job.yaml
charts/splunk-connect-for-snmp/templates/scheduler/deployment.yaml
charts/splunk-connect-for-snmp/templates/traps/deployment.yaml
charts/splunk-connect-for-snmp/templates/worker/deployment.yaml
charts/splunk-connect-for-snmp/values.yaml
config.yaml
entrypoint.sh
pyproject.toml
splunk_connect_for_snmp/common/inventory_record.py
splunk_connect_for_snmp/common/profiles.py
splunk_connect_for_snmp/enrich/tasks.py
splunk_connect_for_snmp/inventory/loader.py
splunk_connect_for_snmp/inventory/tasks.py
splunk_connect_for_snmp/poller.py
splunk_connect_for_snmp/snmp/auth.py
splunk_connect_for_snmp/snmp/context.py
splunk_connect_for_snmp/snmp/manager.py
splunk_connect_for_snmp/snmp/tasks.py
splunk_connect_for_snmp/snmp/varbinds.py
splunk_connect_for_snmp/splunk/tasks.py
values.yaml

refactor: inventory sync, using cleaner dataclasses and K8S job to load inventory avoiding polling
fix: snmpv3 support, dynamic detection of securityEnginerID

fix: Inventory support for SNMPV3

---

poetry.lock

fix: Update scheduler

---

.github/workflows/cd-docs-pdf.yaml
deeplists.tex

fix: add generating pdf from sc4snmp documentation

fix: add generatig pdf from sc4snmp documentation

---

docs/configuration/deployment-configuration.md
docs/configuration/scheduler-configuration.md

fix: doc editorial changes

---

splunk_connect_for_snmp/snmp/manager.py

Address issue with "No more variables left in this MIB View" appearing as attributes

fix: handle short varbind tables

---

splunk_connect_for_snmp/snmp/manager.py

fix: repeat process_snmp_data right after loading mibs (#369)

---

charts/splunk-connect-for-snmp/values.yaml
splunk_connect_for_snmp/celery_config.py

This PR increases rabbitmq timeout from 30 to 40 minutes.
I tested the change on NOVA environment and checked if extraConfiguration for rabbitmq worked.

fix: increase rabbitmq timeout to 40 minutes

---

docs/mib-request.md
mkdocs.yml

Adding documentation for the process of requesting MIBs.
N/A

doc: document way of requesting MIBs

---

docs/gettingstarted/sc4snmp-installation.md
integration_tests/values.yaml

fix: remove unused clusterName

---

splunk_connect_for_snmp/common/schema_migration.py
test/common/test_schema_migration.py

Index was added to attributes collection in Mongo to speed up queries.
I run migration and checked if index is present

fix: add index creation

---

charts/splunk-connect-for-snmp/templates/traps/service.yaml

This PR makes externalTrafficPolicy of traps service configurable.
Tested locally.

fix: make externalTrafficPolicy configurable

---

docs/gettingstarted/sc4snmp-installation.md

This PR fixes shared IP inconsistency in the documentation.
N/A

doc: shared IP inconsistency

---

docs/gettingstarted/sck-installation.md
docs/gettingstarted/splunk-requirements.md
mkdocs.yml

This PRs improved the documentation for the Splunk Observability Cloud
N/A

doc: improve documentation for Splunk Observability Cloud

---

integration_tests/splunk_test_utils.py

Utility methods for integration testing
Run python script on Nova instance and verified that requested changes were reflected in Kubernetes cluster

test: utility methods for integration testing

---

.github/dependabot.yml

This PR configures dependant to send PRs to `develop` branch instead of `main` branch.
N/A

chore: update dependabot to send PRs to develop

---

.github/workflows/agreements.yaml
.github/workflows/ci-main.yaml
.github/workflows/release-notes.yaml
integration_tests/README_WALK
integration_tests/automatic_setup.sh
integration_tests/deploy_and_test.sh

This PR:
* updates the way CI installs `poetry`
* uses reusable workflow for agreements and release-notes
N/A

ci: small updates to the pipeline

---

splunk_connect_for_snmp/common/inventory_record.py
splunk_connect_for_snmp/enrich/tasks.py
splunk_connect_for_snmp/inventory/tasks.py
splunk_connect_for_snmp/snmp/manager.py
splunk_connect_for_snmp/traps.py
test/snmp/test_auth.py
test/snmp/test_tasks.py
test/test_walk.py

This is a PR to address some simple issues after running `flake8`.
N/A

refactor: small changes after running flake8

---

splunk_connect_for_snmp/snmp/tasks.py

This PR fixes typo in `load_mibs` function arguments.
It was tested in NOVA environment during integration tests writing

fix: delete unnecessary variable in load_mibs function

---

.gitignore
integration_tests/automatic_setup.sh
integration_tests/scripts/local_run.sh
integration_tests/scripts/set_env.sh

fix: int tests

---

integration_tests/splunk_test_utils.py
integration_tests/test_poller_integration.py
integration_tests/test_trap_integration.py
integration_tests/values.yaml
splunk_connect_for_snmp/inventory/tasks.py

This PR adds following integration tests:
1. Reloading profiles
2. Deleting Profiles
3. Disabling profiles
4. Base smart profiles
5. Field smart profiles
6. V3 Polling
N/A
Ran it locally on nova environment

test: integration tests for polling

---

.github/workflows/ci-main.yaml
integration_tests/scripts/local_run.sh
integration_tests/test_poller_integration.py

This PR wraps integration tests in classes.
N/A
Ran on NOVA environment.

test: organise integration tests

---

.github/workflows/ci-main.yaml
integration_tests/scripts/local_run.sh
integration_tests/test_poller_integration.py
splunk_connect_for_snmp/customtaskmanager.py
splunk_connect_for_snmp/inventory/loader.py
splunk_connect_for_snmp/snmp/manager.py
splunk_connect_for_snmp/snmp/tasks.py
test/snmp/test_get_varbinds.py

This PR fixes problem of the random total_run_count for a small walk.
Tested on Nova environment

fix: small walk integration tests

---

docs/bestpractices.md
docs/configuration/deployment-configuration.md
docs/configuration/mongo-configuration.md
docs/configuration/poller-configuration.md
docs/configuration/rabbitmq-configuration.md
docs/configuration/scheduler-configuration.md
docs/configuration/sim-configuration.md
docs/configuration/snmpv3-configuration.md
docs/configuration/trap-configuration.md
docs/configuration/worker-configuration.md
docs/gettingstarted/sc4snmp-installation.md
docs/gettingstarted/sck-installation.md
docs/gettingstarted/splunk-requirements.md
docs/ha.md
docs/index.md
docs/mib-request.md
docs/planning.md
docs/security.md

This PR provides stylistic errors fixes and removes typos of the documentation.
N/A
N/A
N/A

doc: remove typos, fix stylistic errors

---

charts/splunk-connect-for-snmp/templates/worker/deployment.yaml
integration_tests/test_poller_integration.py
splunk_connect_for_snmp/splunk/tasks.py

This PR adds headers enabling better Telemetry.

fix: enhancing SC4SNMP Telemetry

---

.pre-commit-config.yaml

This PR updates the black version.

fix: update black version

---

docs/bestpractices.md
docs/configuration/deployment-configuration.md
docs/gettingstarted/sck-installation.md
integration_tests/test_poller_integration.py

This PR enhances the documentation about small walk, profiles updates and fixes broken links.
N/A

doc: clarification and adjust integration tests

---

docs/index.md
docs/planning.md

This PR simplify hard to understand parts of the docs and update perf specs for GETs
N/A

doc: improvements

---

.github/workflows/ci-main.yaml
.github/workflows/mike-cleanup.yaml
.github/workflows/mike.yaml

This PR prevents pipeline from creating documentation versions on githubdocs while making PR.
N/A

chore: piepline documentation publishing fix

---

.gitignore
integration_tests/automatic_setup.sh
integration_tests/splunk_test_utils.py
integration_tests/test_poller_integration.py
integration_tests/values.yaml

test: I added test of snmpv3 walk

---

.github/workflows/offline-installation.yaml
create_packages.sh

I run offline installation of the sc4snmp in lab and it was successful

fix: Creating packages for offline installation in the pipeline

---

charts/splunk-connect-for-snmp/templates/worker/_helpers.tpl
docs/configuration/configuring-profiles.md
integration_tests/test_poller_integration.py
splunk_connect_for_snmp/common/profiles.py
splunk_connect_for_snmp/inventory/loader.py
splunk_connect_for_snmp/inventory/tasks.py
splunk_connect_for_snmp/snmp/manager.py
splunk_connect_for_snmp/snmp/tasks.py
test/common/test_profiles.py
test/inventory/test_assign_profiles.py
test/inventory/test_inventory_setup_poller.py
test/inventory/test_loader.py
test/inventory/test_record_validation.py
test/snmp/test_do_work.py
test/test_walk.py

This PR changes the way profiles are being updated into SC4SNMP.

fix: small walk issue

---

docs/gettingstarted/sc4snmp-installation.md
docs/offline-installation.md
docs/offlineinstallation/offline-sc4snmp.md
docs/offlineinstallation/offline-sck.md
mkdocs.yml

doc: I added documentation of SC4SNMP offline installation

---

entrypoint.sh
splunk_connect_for_snmp/snmp/manager.py
splunk_connect_for_snmp/traps.py

This PR:
- fix sender priority issue
- change autoscaling parameters from entrypoint
- add handling all kinds of exceptions for loading mibs
Manual tests

fix: add handling exceptions for loading mibs

---

docs/configuration/snmpv3-configuration.md
docs/configuration/trap-configuration.md

This is the fix of default value so fsecurityEngine for snmpv3 confiugration.
N/A

doc: fix snmpv3 traps issues

---

charts/splunk-connect-for-snmp/templates/traps/deployment.yaml
charts/splunk-connect-for-snmp/values.yaml
docs/configuration/trap-configuration.md
splunk_connect_for_snmp/traps.py

This PR:
1. Fixes bug with broken secrets mounting
2. Allow to configure list of accepted security engine id
Manual tests

fix: security engines in traps

---

charts/splunk-connect-for-snmp/templates/traps/deployment.yaml
charts/splunk-connect-for-snmp/values.yaml
docs/configuration/trap-configuration.md
docs/upgrade.md
mkdocs.yml
splunk_connect_for_snmp/traps.py

This PR fixes:
1. Mounting more than one secret file
2. Defining more than one security engine id
Manual tests, integration tests, test on customer's environment

fix: trap secrets mount and security engine defining

---

docs/gettingstarted/mk8s/k8s-microk8s.md
docs/small-environment.md
mkdocs.yml

doc: documentation for installation on small environments

---

docs/configuration/worker-configuration.md
docs/gettingstarted/sc4snmp-installation.md
docs/small-environment.md
mkdocs.yml

This PR enhances workers' autoscaling documentation.
N/A
N/A
N/A

doc: enhance worker's related configuration

---

docs/bestpractices.md
docs/configuration/deployment-configuration.md
docs/configuration/worker-configuration.md
docs/gettingstarted/sc4snmp-installation.md
docs/gettingstarted/splunk-requirements.md

This PR fixes some parts of the documentation that contains out of date elements.
N/A
N/A
N/A

doc: old documentation cleanup

---

.github/workflows/mike.yaml

This PR brings back the previous version of poetry, for fixing `mike` step of pipeline
N/A
N/A

chore: go back to the previous version of poetry

---

.github/workflows/cd-pages.yaml
charts/splunk-connect-for-snmp/Chart.lock

Update of dependency Helm lock.
N/A

chore: helm lock

---

splunk_connect_for_snmp/common/collection_manager.py
splunk_connect_for_snmp/profiles/base.yaml

Bringing back previous frequency of mandatory profiles.
N/A

fix: bring back mandatory profiles frequency

---

docs/offlineinstallation/offline-microk8s.md
mkdocs.yml

This PR adds some clarification to offline microk8s instalaltion.
N/A

doc: offline installation of microk8s

---

docs/bestpractices.md
docs/gettingstarted/mk8s/k8s-microk8s.md
docs/gettingstarted/sc4snmp-installation.md
docs/gettingstarted/splunk-requirements.md

Add description of a rollover problem.
N/A
N/A
N/A

doc: add documentation about rollover issue

---

docs/offlineinstallation/offline-microk8s.md

This PR fixes doc section of microk8s offline installation, adding metallb and dns.
N/A
N/A

doc: missing dns and metallb

---

docs/javascripts/footer.js
mkdocs.yml

- [ x ] Refactor/improvement
- [ x ] My commit message is [conventional](https://www.conventionalcommits.org/en/v1.0.0/#summary)
- [ x ] I have run pre-commit on all files before creating the PR
- [ x ] I have made corresponding changes to the documentation
- [ x ] New and existing unit tests pass locally with my changes
- [ x ] I have checked my code and corrected any misspellings

Add license for doc

---

README.md
docs/offlineinstallation/offline-microk8s.md

Update hostpath-storage alias in offline documentation
Update Readme to describe what version of documentation to use
N/A
N/A

doc: update hostpath for offline installation and README.md

---

.github/workflows/ci-release-pr.yaml
.github/workflows/ci-release.yaml
create_packages.sh

This PR fixes mlformed link for `docker pull` of otel collector
N/A
N/A

fix: otel image link from dockerhub

---

create_packages.sh

Fix otel collector link for offline installation
N/A
N/A

fix: update quay.io link

---

charts/splunk-connect-for-snmp/Chart.lock

Update mibserver version.
Integrationt ests

fix: bump mibserver

---

docs/offlineinstallation/offline-microk8s.md
docs/offlineinstallation/offline-sc4snmp.md

This PR clarifies offline-installation most common issues.
N/A
N/A

doc: update offline-installation

---

docs/bestpractices.md
docs/configuration/configuring-groups.md
docs/configuration/configuring-profiles.md
docs/configuration/mongo-configuration.md
docs/configuration/poller-configuration.md
docs/configuration/redis-configuration.md
docs/configuration/snmpv3-configuration.md
docs/configuration/step-by-step-poll.md
docs/configuration/trap-configuration.md
docs/configuration/worker-configuration.md
docs/gettingstarted/mk8s/k8s-microk8s.md
docs/gettingstarted/sc4snmp-installation.md
docs/gettingstarted/sck-installation.md
docs/gettingstarted/splunk-requirements.md
docs/ha.md
docs/index.md
docs/offlineinstallation/offline-microk8s.md
docs/offlineinstallation/offline-sc4snmp.md
docs/planning.md
docs/small-environment.md
docs/upgrade.md

This PR enhances documentation.
N/A
N/A

doc:  fixes

---

README.md
docs/configuration/configuring-profiles.md
docs/gettingstarted/sc4snmp-installation.md
docs/offlineinstallation/offline-sc4snmp.md
docs/small-environment.md
integration_tests/scripts/main.tf.tmpl

chore: fixing aws provider terraform version

---

splunk_connect_for_snmp/customtaskmanager.py
splunk_connect_for_snmp/enrich/tasks.py
test/other/test_custom_task_manager.py

This PR fixes the issue of persistence of Redis configuration.

fix: redis issue

---

.github/workflows/ci-main.yaml
charts/splunk-connect-for-snmp/templates/inventory/job.yaml
charts/splunk-connect-for-snmp/templates/scheduler/deployment.yaml
charts/splunk-connect-for-snmp/templates/worker/poller/deployment.yaml
charts/splunk-connect-for-snmp/templates/worker/sender/deployment.yaml
charts/splunk-connect-for-snmp/templates/worker/trap/deployment.yaml
integration_tests/automatic_setup.sh
integration_tests/test_poller_integration.py

Update integration tests with:
1. Checking if metaLLB was successfully installed
2. Increasing edit time for routers group
Change way of mounting secrets to pods.
Integration/manual tests.

fix: integration tests, mounting secrets to pods

---

integration_tests/README.md
test/README.md

This PR adds Readme about how to run tests.
N/A
N/A

test: add README.md file for running tests

---

splunk_connect_for_snmp/splunk/tasks.py

The deletion of the unnecessary print statement (creates a lot of logs).
N/A
N/A

fix: delete unnecessary print statement

---

charts/splunk-connect-for-snmp/templates/traps/deployment.yaml

This fix eliminates lookup helm function from the trap template.
Integration tests, manual tests

fix: traps delete lookup for secrets

---

.github/workflows/mike.yaml

Fix mike step in the CI.
N/A
N/A

chore: update mike dependencies

---

.github/workflows/mike.yaml

chore: install setuptools for mike

---

charts/splunk-connect-for-snmp/Chart.lock

Update version of the mibserver
Integration tests

helm: update mibserver 

---

docs/gettingstarted/sc4snmp-installation.md

Comment out poller configuration to avoid problems with poller.usernameSecrets
N/A
N/A
N/A

doc: comment out poller configuration

---

.github/workflows/cd-pages.yaml
charts/splunk-connect-for-snmp/Chart.lock
charts/splunk-connect-for-snmp/Chart.yaml
charts/splunk-connect-for-snmp/templates/inventory/job.yaml
charts/splunk-connect-for-snmp/templates/scheduler/deployment.yaml
charts/splunk-connect-for-snmp/templates/worker/poller/deployment.yaml
charts/splunk-connect-for-snmp/templates/worker/sender/deployment.yaml
charts/splunk-connect-for-snmp/templates/worker/trap/deployment.yaml
create_packages.sh

Fix of helm issue:
```
Error: UPGRADE FAILED: template: splunk-connect-for-snmp/templates/worker/trap/deployment.yaml:53:29: executing "splunk-connect-for-snmp/templates/worker/trap/deployment.yaml" at <.Values.poller.usernameSecrets>: nil pointer evaluating interface {}.usernameSecrets
```
When the `values.yaml` config is following:
```
poller:
#usernameSecrets:
```
N/A
N/A

helm: usernameSecrets helm

---

.github/workflows/cd-pages.yaml
charts/splunk-connect-for-snmp/Chart.lock
charts/splunk-connect-for-snmp/Chart.yaml
create_packages.sh

Upgrading MongoDB and Redis Helm dependency to the newest versions.

fix: helm dependency update

---

CHANGELOG.md

This PR adds CHANGELOG.md file 
N/A
N/A

fix: add Changelog and bump release

---

Makefile
rendered/manifests/tests/splunk-connect-for-snmp/templates/common/scheduler-config.yaml
rendered/manifests/tests/splunk-connect-for-snmp/templates/common/scheduler-inventory.yaml
rendered/manifests/tests/splunk-connect-for-snmp/templates/common/traps-config.yaml
rendered/manifests/tests/splunk-connect-for-snmp/templates/inventory/job.yaml
rendered/manifests/tests/splunk-connect-for-snmp/templates/scheduler/deployment.yaml
rendered/manifests/tests/splunk-connect-for-snmp/templates/scheduler/pdb.yaml
rendered/manifests/tests/splunk-connect-for-snmp/templates/scheduler/serviceaccount.yaml
rendered/manifests/tests/splunk-connect-for-snmp/templates/sim/pdb.yaml
rendered/manifests/tests/splunk-connect-for-snmp/templates/tests/test-connection.yaml
rendered/manifests/tests/splunk-connect-for-snmp/templates/traps/deployment.yaml
rendered/manifests/tests/splunk-connect-for-snmp/templates/traps/pdb.yaml
rendered/manifests/tests/splunk-connect-for-snmp/templates/traps/service.yaml
rendered/manifests/tests/splunk-connect-for-snmp/templates/traps/serviceaccount.yaml
rendered/manifests/tests/splunk-connect-for-snmp/templates/worker/pdb.yaml
rendered/manifests/tests/splunk-connect-for-snmp/templates/worker/poller/deployment.yaml
rendered/manifests/tests/splunk-connect-for-snmp/templates/worker/sender/deployment.yaml
rendered/manifests/tests/splunk-connect-for-snmp/templates/worker/serviceaccount.yaml
rendered/manifests/tests/splunk-connect-for-snmp/templates/worker/trap/deployment.yaml
rendered/values.yaml

This PR provides `make render` step, so that we have control over changes in Helm template.
N/A
N/A

chore: add make render

---

CHANGELOG.md
docs/mib-request.md

This PR:
1. Documents how to verify if the mibserver compiled files correctly
2. Updates the CHANGELOG
N/A
N/A

doc: document mibserver troubleshooting and update CHANGELOG

---

.pre-commit-config.yaml
charts/splunk-connect-for-snmp/Chart.lock
charts/splunk-connect-for-snmp/Chart.yaml
create_packages.sh
docs/mib-request.md
docs/offlineinstallation/offline-sc4snmp.md
integration_tests/automatic_setup.sh

This PR:
1. Fixes using local mibserver compilation in offline environment
2. Fixes failing mibserver package for offline installation
3. Updates docs
Integration tests

fix: offline mibserver and docs

---

.github/workflows/mike.yaml

chore: add missing setuptools for mike

---

.github/workflows/mike.yaml

chore: add gnome-keyring

---

README.md
integration_tests/automatic_setup.sh

test: adding syntax from poetry >= 1.2

---

.github/workflows/offline-installation.yaml
.github/workflows/release-notes.yaml

Fix problem with workflow permissions.
N/A
N/A

fix: workflow permissions

---

.github/workflows/cd-pages.yaml
docs/gettingstarted/sc4snmp-installation.md

This PR fixes Helm gh-actions permissions pipeline
N/A
N/A

fix: GitHub actions Helm permissions

---

charts/splunk-connect-for-snmp/values.yaml
docs/configuration/step-by-step-poll.md
docs/gettingstarted/sc4snmp-installation.md
mkdocs.yml
rendered/manifests/tests/splunk-connect-for-snmp/templates/common/scheduler-config.yaml
rendered/manifests/tests/splunk-connect-for-snmp/templates/common/scheduler-inventory.yaml
rendered/manifests/tests/splunk-connect-for-snmp/templates/common/traps-config.yaml
rendered/manifests/tests/splunk-connect-for-snmp/templates/inventory/job.yaml
rendered/manifests/tests/splunk-connect-for-snmp/templates/scheduler/deployment.yaml
rendered/manifests/tests/splunk-connect-for-snmp/templates/scheduler/pdb.yaml
rendered/manifests/tests/splunk-connect-for-snmp/templates/serviceaccount.yaml
rendered/manifests/tests/splunk-connect-for-snmp/templates/sim/pdb.yaml
rendered/manifests/tests/splunk-connect-for-snmp/templates/tests/test-connection.yaml
rendered/manifests/tests/splunk-connect-for-snmp/templates/traps/deployment.yaml
rendered/manifests/tests/splunk-connect-for-snmp/templates/traps/pdb.yaml
rendered/manifests/tests/splunk-connect-for-snmp/templates/traps/service.yaml
rendered/manifests/tests/splunk-connect-for-snmp/templates/worker/pdb.yaml
rendered/manifests/tests/splunk-connect-for-snmp/templates/worker/poller/deployment.yaml
rendered/manifests/tests/splunk-connect-for-snmp/templates/worker/sender/deployment.yaml
rendered/manifests/tests/splunk-connect-for-snmp/templates/worker/trap/deployment.yaml

This PR provides some minor enhancements for the documentation.
It adds logLevels to values.yaml and more profiles examples.
N/A
N/A

doc: minor enhancements

---

CHANGELOG.md

This PR will update the version of the changelog and versioning of the beta package with semantic release.
N/A
N/A
N/A

feat: prepare 1.9.0 release

---

.github/workflows/mike.yaml
.github/workflows/update-tags.yaml

Fix permission issues in pipeline
N/A
N/A
N/A

chore: update permissions

---

.github/workflows/ci-main.yaml
integration_tests/automatic_setup.sh
integration_tests/splunk_test_utils.py

Moving test execution into github
all tests are now passing in pipeline and also it is possible to run them locally

[Integration tests] moving tests into GitHub

---

integration_tests/automatic_setup.sh

This PR fixes failing v3 integration tests.

Check v3 poller

---

.github/workflows/ci-release.yaml

Use fixed version of semantic-release-replace-plugin

fix: update semantic-release-replace-plugin

---

.github/workflows/agreements.yaml

chore: update github permission

---

poetry.lock

Update pygments from 2.13.0 to 2.15.0

chore: bump pygments from 2.13.0 to 2.15.0

---

charts/splunk-connect-for-snmp/values.yaml
examples/basic_template.md
rendered/manifests/tests/splunk-connect-for-snmp/templates/worker/poller/deployment.yaml
rendered/manifests/tests/splunk-connect-for-snmp/templates/worker/sender/deployment.yaml
rendered/manifests/tests/splunk-connect-for-snmp/templates/worker/trap/deployment.yaml
rendered/manifests/tests_autoscaling_enabled/splunk-connect-for-snmp/templates/worker/poller/deployment.yaml
rendered/manifests/tests_autoscaling_enabled/splunk-connect-for-snmp/templates/worker/sender/deployment.yaml
rendered/manifests/tests_autoscaling_enabled/splunk-connect-for-snmp/templates/worker/trap/deployment.yaml
rendered/manifests/tests_autoscaling_enabled_deprecated/splunk-connect-for-snmp/templates/worker/poller/deployment.yaml
rendered/manifests/tests_autoscaling_enabled_deprecated/splunk-connect-for-snmp/templates/worker/sender/deployment.yaml
rendered/manifests/tests_autoscaling_enabled_deprecated/splunk-connect-for-snmp/templates/worker/trap/deployment.yaml
rendered/manifests/tests_only_polling/splunk-connect-for-snmp/templates/worker/poller/deployment.yaml
rendered/manifests/tests_only_polling/splunk-connect-for-snmp/templates/worker/sender/deployment.yaml
rendered/manifests/tests_only_traps/splunk-connect-for-snmp/templates/worker/sender/deployment.yaml
rendered/manifests/tests_only_traps/splunk-connect-for-snmp/templates/worker/trap/deployment.yaml
rendered/manifests/tests_probes_enabled/splunk-connect-for-snmp/templates/worker/poller/deployment.yaml
rendered/manifests/tests_probes_enabled/splunk-connect-for-snmp/templates/worker/sender/deployment.yaml
rendered/manifests/tests_probes_enabled/splunk-connect-for-snmp/templates/worker/trap/deployment.yaml

Updating comments in values.yaml as they were describing wrong section of settings.
Added default eventIndex and metricsIndex 

chore: update documentation in values

---

.github/workflows/agreements.yaml

Reverts splunk/splunk-connect-for-snmp#785

Revert "chore/test-perms"

---

docs/bestpractices.md
docs/gettingstarted/sc4snmp-installation.md

Move instruction about uninstallation from Troubleshooting to Getting Started section.
N/A

doc: move uninstallation instruction

---

.github/workflows/agreements.yaml

ci: cla-agreements

---

docs/bestpractices.md

Add documentation about immutable field error to troubleshooting section.
N/A
N/A

chore: update troubleshooting docs

---

poetry.lock
pyproject.toml

This reverts commit 2dee2c69219eb23ab831f8ac8847b7c371383bdf.

revert "chore(deps): update dependency celery to v5.3.1 (#809)"

---

integration_tests/test_poller_integration.py

Increase wait time for snmp v3 walk integration test.
N/A
N/A
N/A

test: snmpv3 walk

---

CHANGELOG.md
docs/configuration/configuring-profiles.md
integration_tests/test_poller_integration.py
splunk_connect_for_snmp/inventory/tasks.py
test/inventory/test_conditional_profiles.py

Improving conditional profiles by adding option to negate requested operation and adding filtering with regex.
manual tests, unit tests, integration tests

fix: update conditional profiles

---

docs/configuration/configuring-profiles.md

Fix parsing in documentation.
N/A
N/A 
N/A

chore: update docs

---

docs/configuration/poller-configuration.md

Adding documentation about updating inventory from csv file.
N/A
N/A

docs: inventory from csv

---

charts/splunk-connect-for-snmp/values.yaml

Add udpConnectionTimeout default value to value.yaml
N/A
N/A

chore: add udp to values.yaml

---

.github/workflows/cd-docs-pdf.yaml
.github/workflows/update-tags.yaml
renovate.json

Update permissions for failing workflows and update renovate configuration
N/A
N/A
N/A

chore: update renovate

---

.gitignore
.gitlab-ci.yml
sonar-project.properties

Sonarqube configuration
- [x ] New feature
Tested locally
- [x ] My commit message is [conventional](https://www.conventionalcommits.org/en/v1.0.0/#summary)
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have checked my code and corrected any misspellings

chore: sonarqube configuration

---

integration_tests/prepare_splunk.sh
poetry.lock
pyproject.toml

- update celery version to 5.3.4
- update redbeat

fix: update celery to 5.3.4

---

docs/configuration/trap-configuration.md

Add documentation regarding updating traps values.
N/A
N/A

docs: update trap pod

---

CHANGELOG.md

Version update before release
N/A
N/A
N/A

Chore/update changelog 1.9.3

---

.github/workflows/ci-main.yaml

Replace repository workflow as old one got deprecated.
N/A
N/A
N/A

Chore: update semgrep

---

splunk_connect_for_snmp/gopoller/snmp.go

Add method to do snmp get call in Go code.
manual test

fix: add getcmd

---

docs/docker-compose.md
mkdocs.yml

fix: change the text
Note in documentation about new POC of docker-compose deployment

fix: note about docker compose POC

---

splunk_connect_for_snmp/gopoller/.gitignore
splunk_connect_for_snmp/gopoller/auth.go
splunk_connect_for_snmp/gopoller/custom_structs.go
splunk_connect_for_snmp/gopoller/errors.go
splunk_connect_for_snmp/gopoller/snmp.go

Add authentication for snmpv3 in go poller
Manual tests

feat: add snmpv3 authentication

---

splunk_connect_for_snmp/snmp/manager.py
splunk_connect_for_snmp/snmp/tasks.py
splunk_connect_for_snmp/snmp/varbinds_resolver.py
splunk_connect_for_snmp/walk.py
test/snmp/test_do_work.py
test/snmp/test_get_varbinds.py
test/snmp/test_mibs.py
test/snmp/test_process_snmp_data.py
test/snmp/test_tasks.py
test/test_walk.py

Changes Poller to support calling either Go or Python implementation of polling. 
manual test, unit test

fix: add poller interface

---

.fossa.yml
.github/workflows/ci-main.yaml
pyproject.toml

Update dev dependencies tag in poetry to be ignored in fossa checks

chore: update fossa exclude paths

---

Dockerfile
charts/splunk-connect-for-snmp/templates/worker/_helpers.tpl
charts/splunk-connect-for-snmp/values.yaml
splunk_connect_for_snmp/gopoller/auth.go
splunk_connect_for_snmp/gopoller/common.go

This PR updates the Dockerfile in order to build sc4snmp with a new poller written in GO. This PR also adds configuration of logger in the new GO poller.
Manual testing

feat: build sc4snmp with gopoller and add logger configuration in go code

---

splunk_connect_for_snmp/common/collection_manager.py
splunk_connect_for_snmp/common/custom_translations.py
splunk_connect_for_snmp/common/inventory_processor.py
splunk_connect_for_snmp/enrich/tasks.py
splunk_connect_for_snmp/inventory/loader.py
splunk_connect_for_snmp/inventory/tasks.py
splunk_connect_for_snmp/snmp/auth.py
splunk_connect_for_snmp/snmp/manager.py
splunk_connect_for_snmp/snmp/tasks.py
splunk_connect_for_snmp/splunk/tasks.py
splunk_connect_for_snmp/traps.py
ui_tests/exceptions_tests.py
ui_tests/splunk_search.py

Fix error handling issues found by sonarqube

fix: fix error handling issues from sonarqube

---

integration_tests/automatic_setup.sh
splunk_connect_for_snmp/celery_config.py
splunk_connect_for_snmp/common/collection_manager.py
splunk_connect_for_snmp/common/custom_translations.py
splunk_connect_for_snmp/common/inventory_processor.py
splunk_connect_for_snmp/enrich/tasks.py
splunk_connect_for_snmp/inventory/loader.py
splunk_connect_for_snmp/inventory/tasks.py
splunk_connect_for_snmp/poller.py
splunk_connect_for_snmp/snmp/manager.py
splunk_connect_for_snmp/snmp/tasks.py
splunk_connect_for_snmp/splunk/tasks.py
splunk_connect_for_snmp/traps.py

Fix issues with dotenv imports.
manual, unit

fix: dotenv error

---

charts/splunk-connect-for-snmp/templates/worker/_helpers.tpl
charts/splunk-connect-for-snmp/values.yaml
splunk_connect_for_snmp/snmp/tasks.py
splunk_connect_for_snmp/walk.py

Add flag to enable using Go poller from values.yaml
manual testing

feat: add switch to Go

---

splunk_connect_for_snmp/common/collection_manager.py
splunk_connect_for_snmp/common/schema_migration.py
splunk_connect_for_snmp/inventory/tasks.py
splunk_connect_for_snmp/poller.py
splunk_connect_for_snmp/snmp/auth.py
splunk_connect_for_snmp/snmp/manager.py
splunk_connect_for_snmp/splunk/tasks.py
splunk_connect_for_snmp/traps.py
ui_tests/logger/logger.py
ui_tests/pages/helper.py
ui_tests/pages/profiles_page.py
ui_tests/tests/test_splunk_integration.py
ui_tests/webdriver/webriver_factory.py

Remove unnecessary comments, code lines and variables spotted in sonarqube report.
manual test, integration test

chore: remove redundant code

---

.github/workflows/ci-main.yaml
docs/gui/enable-gui.md

Update of documentation for UI that adds template for initial valuesFileName

docs: add template for ui file

---

docs/gui/enable-gui.md
splunk_connect_for_snmp/snmp/auth.py
splunk_connect_for_snmp/snmp/manager.py
splunk_connect_for_snmp/snmp/varbinds_resolver.py
test/snmp/test_auth.py

Update log and error messages to include ip address if needed.

Fix: improve errors message

---

mkdocs.yml

Fix  mkdocs.yml formatting

---

.github/pull_request_template.md
poetry.lock

Security update from dependabot for:
- dnspython to v2.6.1
- idna to v3.7
unit test, manual test

chore: security update

---

splunk_connect_for_snmp/customtaskmanager.py
splunk_connect_for_snmp/enrich/tasks.py
splunk_connect_for_snmp/inventory/tasks.py
splunk_connect_for_snmp/snmp/manager.py
splunk_connect_for_snmp/snmp/varbinds_resolver.py
splunk_connect_for_snmp/traps.py

Fix issues related to operators and imports from sonarqube report.
unit tests, integration test, manual test

chore: fix operators

---

CHANGELOG.md
splunk_connect_for_snmp/inventory/loader.py

fix a bug with values.yaml not being loaded to the UI while migrating to SC4SNMP-UI

fix: fix a bug with values.yaml not being loaded to the UI while migrating to SC4SNMP-UI

---

.github/workflows/ci-release.yaml

chore: fix semantic plugin

---

splunk_connect_for_snmp/inventory/tasks.py
splunk_connect_for_snmp/snmp/auth.py
splunk_connect_for_snmp/snmp/manager.py
splunk_connect_for_snmp/snmp/tasks.py
splunk_connect_for_snmp/splunk/tasks.py
splunk_connect_for_snmp/traps.py
test/snmp/test_auth.py
test/snmp/test_do_work.py
test/snmp/test_get_varbinds.py
test/snmp/test_mibs.py
test/snmp/test_process_snmp_data.py
test/snmp/test_utils.py
ui_tests/pages/profiles_page.py
ui_tests/tests/test_error_handling_and_complex_scenarios.py
ui_tests/tests/test_inventory_basic.py
ui_tests/tests/test_profiles_basic.py
ui_tests/tests/test_save_update_configuration.py
ui_tests/tests/test_splunk_integration.py

Rename variables to match convention

chore: rename variables to match convention

---

poetry.lock

Security update for jinja2 to v3.1.4
unit test

chore: jinja2 security update

---

CHANGELOG.md
Dockerfile
docker_compose/docker-compose-inventory.yaml
docker_compose/docker-compose-scheduler.yaml
docker_compose/docker-compose-traps.yaml
docker_compose/docker-compose-worker-poller.yaml
docker_compose/docker-compose-worker-sender.yaml
docker_compose/docker-compose-worker-trap.yaml

Update UID in docker container from root to 1000
Manual and integration tests

chore: update dockerfile

---

splunk_connect_for_snmp/inventory/loader.py
ui_tests/pages/groups_page.py
ui_tests/pages/inventory_page.py
ui_tests/pages/profiles_page.py
ui_tests/tests/test_error_handling_and_complex_scenarios.py
ui_tests/tests/test_groups_basic.py
ui_tests/tests/test_inventory_basic.py
ui_tests/tests/test_save_update_configuration.py
ui_tests/tests/test_splunk_integration.py
ui_tests/webdriver/webriver_factory.py

Replace unnecessary f-strings with strings.
ui test, unit test

chore: fix fstrings

---

docker_compose/manage_secrets.py
ui_tests/tests/test_splunk_integration.py

Fix duplicated strings.
- [ x] Refactor/improvement
ui test

chore: fix duplications

---

CHANGELOG.md
charts/splunk-connect-for-snmp/values.schema.json
charts/splunk-connect-for-snmp/values.yaml
examples/lightweight_installation.yaml
rendered/manifests/tests/splunk-connect-for-snmp/templates/worker/trap/deployment.yaml
rendered/manifests/tests_autoscaling_enabled/splunk-connect-for-snmp/templates/worker/trap/deployment.yaml
rendered/manifests/tests_autoscaling_enabled_deprecated/splunk-connect-for-snmp/templates/worker/trap/deployment.yaml
rendered/manifests/tests_enable_ui/splunk-connect-for-snmp/templates/worker/trap/deployment.yaml
rendered/manifests/tests_only_traps/splunk-connect-for-snmp/templates/worker/trap/deployment.yaml
rendered/manifests/tests_probes_enabled/splunk-connect-for-snmp/templates/worker/trap/deployment.yaml

This PR adds values.schema.json to validate `values.yaml` in helm chart
Manual testing

Fix: add values.schema.json validation

---

pyproject.toml

Temporary fossa fix to missing dependencies.

chore: temporary fossa fix

---

charts/splunk-connect-for-snmp/templates/common/scheduler-config.yaml
charts/splunk-connect-for-snmp/templates/scheduler/deployment.yaml
charts/splunk-connect-for-snmp/templates/worker/_helpers.tpl
charts/splunk-connect-for-snmp/values.yaml
docker_compose/docker-compose-scheduler.yaml
docker_compose/docker-compose-traps.yaml
docs/configuration/values-params-description.md
docs/gui/enable-gui.md
rendered/manifests/tests/splunk-connect-for-snmp/templates/scheduler/deployment.yaml
rendered/manifests/tests_autoscaling_enabled/splunk-connect-for-snmp/templates/scheduler/deployment.yaml
rendered/manifests/tests_autoscaling_enabled_deprecated/splunk-connect-for-snmp/templates/scheduler/deployment.yaml
rendered/manifests/tests_enable_ui/splunk-connect-for-snmp/templates/scheduler/deployment.yaml
rendered/manifests/tests_only_polling/splunk-connect-for-snmp/templates/scheduler/deployment.yaml
rendered/manifests/tests_probes_enabled/splunk-connect-for-snmp/templates/scheduler/deployment.yaml
splunk_connect_for_snmp/poller.py

Adds description of values in documentation and removes unused variables.
manual test

Chore: review and document values

---

docker_compose/manage_secrets.py
mkdocs.yml
splunk_connect_for_snmp/enrich/tasks.py
splunk_connect_for_snmp/inventory/tasks.py
splunk_connect_for_snmp/snmp/manager.py
ui_tests/splunk_search.py

Fix sonarqube issues. 
unit test

chore: add comments and errors class

---

charts/splunk-connect-for-snmp/values.schema.json

Add image to UI schema section.
ui test

chore: update schema

---

.github/workflows/cd-docs-pdf.yaml
.github/workflows/offline-installation.yaml
create_packages.sh

Fixes workflows:
- offline-installation
- cd-docs-pdf 
manual test

fix: fix workflows

---

charts/splunk-connect-for-snmp/Chart.lock

Update chart with mibserver v1.15.11

Chore: update chart

---

CHANGELOG.md

Update version for release 1.11.0

Chore: update changelog

---

.pre-commit-config.yaml
splunk_connect_for_snmp/snmp/manager.py

Fix of failing pre-commit workflow
github actions

chore: update pre-commit config

---

pyproject.toml

Reverting code to test the fossa workflow without workaround for ignoring dev dependency packages. 

chore: fossa update

---

splunk_connect_for_snmp/snmp/manager.py
test/snmp/test_mibs.py
test/snmp/test_process_snmp_data.py

Refactor of process_snmp_data in manager.py 
unit, integration, manual

fix: refactor process snmp data

---

charts/splunk-connect-for-snmp/Chart.lock
integration_tests/automatic_setup_compose.sh
integration_tests/automatic_setup_microk8s.sh
integration_tests/deploy_and_test.sh

Fix: broken tests

---

CHANGELOG.md

Docs: update changelog

---

docs/troubleshooting/polling-issues.md

Fixed linking issues for documentation. 
manual

Docs: update links

---

docker_compose/manage_logs.py
docker_compose/manage_secrets.py

Fix complexity for create_secrets method
integration tests

fix: refactor create secrets

---

CHANGELOG.md
charts/splunk-connect-for-snmp/templates/sim/deployment.yaml
charts/splunk-connect-for-snmp/values.schema.json
charts/splunk-connect-for-snmp/values.yaml
docs/configuration/values-params-description.md

Adds nodeSelector and podAntiAffinity to sim chart. 
manual

fix: add nodeselector for sim

---

.github/workflows/cd-dashboard-release.yaml
CHANGELOG.md
dashboard/dashboard.xml
docs/dashboard.md
mkdocs.yml

fix: trim in dashboard port number of SNMP device address

---

docs/troubleshooting/configuring-logs.md
docs/troubleshooting/docker-commands.md
docs/troubleshooting/k8s-commands.md
docs/troubleshooting/polling-issues.md
mkdocs.yml

Adds documentation about troubleshooting commands for docker deployment.
manual

docs: add docker troubleshooting instructions

---

.github/workflows/ci-main.yaml
.github/workflows/mike.yaml

Fix failing workflows
workflow test

chore: update mike workflow

---

splunk_connect_for_snmp/snmp/manager.py

Refactor do_work method.
manual, unit, integrational

fix: refactor do work

---

CHANGELOG.md

Update changelog before release of 1.12.0

chore: update changelog 1.12.0

---

.github/workflows/ci-main.yaml

chore: upgrade deprecated semgrep

---

.semgrepignore

chore: semgrep exclude tests from analyze

---

CHANGELOG.md
integration_tests/automatic_setup_compose.sh

Update changelog for version 1.12.1.

chore: update version

---

CHANGELOG.md
splunk_connect_for_snmp/profiles/base.yaml

Update baseIf profile with IF-MIB.ifOperStatus
unit, integration tests

Fix: update baseif

---

splunk_connect_for_snmp/inventory/loader.py

Refactor of configure ui database method.
integration

Fix: refactor configure UI database

---

splunk_connect_for_snmp/inventory/loader.py
ui_tests/tests/test_splunk_integration.py

Refactor of load()
manual, unit, integration

fix: refactor load

---

sonar-project.properties

chore: update sonar exclusions list

---

dashboard/dashboard.xml
docs/dashboard.md
docs/microk8s/configuration/values-params-description.md
docs/microk8s/mk8s/k8s-microk8s.md
docs/microk8s/sc4snmp-installation.md
docs/microk8s/splunk-requirements.md

Update links and some typos in documentation. 
manual

Chore: upate doc links

---

.github/workflows/ci-main.yaml
.github/workflows/ci-ui-tests.yaml

chore: run all test suite when merging on develop

---

CHANGELOG.md
integration_tests/test_trap_integration.py
integration_tests/traps-config.yaml
integration_tests/values.yaml
splunk_connect_for_snmp/traps.py

Fix adding communities for traps with v1. 
unit, manual, integration

Fix: receive v1 traps

---

.github/workflows/mike.yaml

Updates mike to use python with version 3.10 instead of 3.12.
pipeline

chore: update mike.yaml

---

docs/internal/pysnmp_debug.md

Internal documentation for troubleshooting. 
N/A

chore: pysnmp debug docs

---

charts/splunk-connect-for-snmp/templates/worker/_helpers.tpl
rendered/manifests/tests/splunk-connect-for-snmp/templates/worker/trap/deployment.yaml
rendered/manifests/tests_autoscaling_enabled/splunk-connect-for-snmp/templates/worker/trap/deployment.yaml
rendered/manifests/tests_autoscaling_enabled_deprecated/splunk-connect-for-snmp/templates/worker/trap/deployment.yaml
rendered/manifests/tests_enable_ui/splunk-connect-for-snmp/templates/worker/trap/deployment.yaml
rendered/manifests/tests_only_traps/splunk-connect-for-snmp/templates/worker/trap/deployment.yaml
rendered/manifests/tests_probes_enabled/splunk-connect-for-snmp/templates/worker/trap/deployment.yaml
splunk_connect_for_snmp/snmp/tasks.py

Refactor trap method.
manual, unit, integration

fix: refactor trap

---

docs/microk8s/mk8s/k8s-microk8s.md

Add to documentation note about possibility to use different storage types.
manual

docs: recommend storage

---

docs/troubleshooting/configuring-logs.md

Add description for common Splunk queries to filter logs for issues.
n/a

Docs: add logs queries

---

charts/splunk-connect-for-snmp/values.schema.json
charts/splunk-connect-for-snmp/values.yaml

Related to issue #1111, adds nodeSelector to worker in values.yaml
manual, integration

Chore: add worker nodeselector

---

CHANGELOG.md
Dockerfile

fix: upgrade base image

---

.github/workflows/ci-docker-deployment.yaml
.github/workflows/ci-ui-tests.yaml
.github/workflows/offline-installation.yaml
ui_tests/tests/test_splunk_integration.py

Changing the test timers and update python version in workflows to 3.10.
ui tests

Test: improve stability

---

CHANGELOG.md
splunk_connect_for_snmp/snmp/auth.py
test/snmp/test_auth.py
ui_tests/tests/test_splunk_integration.py

Fix for dns resolution failing when only ipv4 is enabled.
manual, integration

fix: dns ipv4 translation

---

.github/workflows/offline-installation.yaml

chore: update python in offline install

---

.github/ISSUE_TEMPLATE/bug---escalation-report.md 
.github/ISSUE_TEMPLATE/feature_request.md

Adds issue templates for github

Chore: add github templates

---

docs/microk8s/configuration/deployment-configuration.md
docs/microk8s/sc4snmp-installation.md
examples/basic_template.yaml

Adds the basic template for configuration to facilitate the process of configuring the sc4snmp.
-

chore: add config template

---

.github/workflows/ci-main.yaml
Dockerfile

Add trivy scanner to CI to make auto check that need prodsec
Runned whole test suite and run it locally

fix: scan docker image on CVEs in CI

---

CHANGELOG.md

Prepare release notes for release
No needed

chore: prepare release notes for release

---

CHANGELOG.md
charts/splunk-connect-for-snmp/values.schema.json

Fixes https://github.com/splunk/splunk-connect-for-snmp/issues/1189
Manual tests

fix: schema validation external traps

---

Dockerfile
docs/dockercompose/8-offline-installation.md
integration_tests/.env
rendered/values_mongodb_custom_image.yaml

Fix offline installation `docker compose` documentation 
Integration tests, manual tests

fix: update offline docker compose installation and dependency update

---

charts/splunk-connect-for-snmp/values.yaml
integration_tests/pytest.ini
integration_tests/test_poller_integration.py
integration_tests/values.yaml

Currently, SC4SNMP fails with `Failed to pull image "docker.io/bitnami/os-shell:12-debian-12-r30": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/bitnami/os-shell:12-debian-12-r30": failed to unpack image on snapshotter overlayfs: unexpected media type text/html for sha256:7c367a13a07e134567b4741d513fdc8dbd6424fc7e8d2552434cc354cf943e2b: not found`
The repository has to be changed to `bitnamilegacy`

fix: update mongo mongodb volumePermissions image
