deploy/sc4snmp/traps-deployment.yaml
deploy/sc4snmp/traps-service.yaml

Raise this PR to close #34 
- Set the host to be the trap sender's IP address instead of the trap sender's hostname
- Resolve the cluster network issue to get the correct sender's IP address instead of the masking IP when sending traps from external machines.

Fix trap host issue

---

docs/source/gettingstarted.rst
pyproject.toml
test/README_INTEGRATION_TESTS
test/deploy_and_test.sh
test/install_microk8s.sh

- we can now run our integration tests on CentOS as well
- this is mainly used to verify that we have a working
Kubernetes running on CentOS, because as we know all
the components are running on a separated container

feat: ADDON-35792

---

docs/source/gettingstarted.rst

- when using *. as a bullet list, for some reason the code-block
disappeared. Now it is visible again

fix (doc): broken tags in documentation

---

deploy/sc4snmp/sck.yaml
deploy/sck/sck_147.yaml

As requested in https://github.com/splunk/splunk-connect-for-snmp/pull/75 updated yaml to use yaml list to make code easier to read. 
I have chosen to keep it as simple as it gets and accept the default polling of 15m. Full options list for objects is here, incase we want to iterate. There is namespace scoping but it looks like you need to define an input per type per namespace, so i skipped for now while I check with @rockb1017 
https://github.com/splunk/splunk-connect-for-kubernetes/blob/eab9ab19617fcd153e47aac417c80727f7edf0e7/helm-chart/splunk-connect-for-kubernetes/charts/splunk-kubernetes-objects/values.yaml#L76-L118
Tests:
Deployed from main, then used this branch to delete and redeploy sck helmrelease with objects enabled and with yaml list version of config. Here is the result on …

enhance object collection code readability

---

charts/templates/poller/scheduler-deployment.yaml
charts/templates/poller/worker-deployment.yaml
charts/values.yaml
charts/values.yaml.example

Workers should be HA by default. Depends on PR https://github.com/splunk/splunk-connect-for-snmp-poller/pull/190
Moved the image info from worker to "poller" as this is shared between poller and scheduler and both must be the same

feat: Set worker replica's to two by default

---

config.yaml.example

This PR removes config.yaml file, which is injected by Helm during the installation. 
In order to run SC4SNMP locally `config.yaml.example` must be renamed to `config.yaml`, and env variable:
```
export CONFIG_PATH=<absolute_path>/snmp/splunk-connect-for-snmp/splunk_connect_for_snmp/config.yaml
```
same for inventory:
```
export INVENTORY_PATH=<absolute_path>/snmp/splunk-connect-for-snmp/splunk_connect_for_snmp/inventory.csv
```

fix: update config.yaml to config.yaml.example

---

charts/splunk-connect-for-snmp/values.yaml

Fix an issue that cause:
```
Waiting for amqp://sc4snmp:*****@snmp-rabbitmq:5672/
Still waiting for amqp://sc4snmp:*****@snmp-rabbitmq:5672/ (20s elapsed)
Still waiting for amqp://sc4snmp:*****@snmp-rabbitmq:5672/ (40s elapsed)
Still waiting for amqp://sc4snmp:*****@snmp-rabbitmq:5672/ (60s elapsed)
Still waiting for amqp://sc4snmp:*****@snmp-rabbitmq:5672/ (80s elapsed)
Still waiting for amqp://sc4snmp:*****@snmp-rabbitmq:5672/ (100s elapsed)
```

fix: delete full name for mongo and rabbitmq

---

.github/workflows/cd-pages.yaml

This can be the fix for:
```
error: failed to push some refs to 'https://github.com/splunk/splunk-connect-for-snmp'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details."
```
according to https://github.com/jimporter/mike/issues/60

fix: delete rebase from mike

---

entrypoint.sh
splunk_connect_for_snmp/snmp/tasks.py

Turns out we need to have `max_retries` parameter in celery task, `retry_backoff_max` doesn't stop the tasks

fix: change retries for walk

---

splunk_connect_for_snmp/celery_config.py

For "long" tasks like snmp work celery recommends we only lock one task

fix: only lock one item per thread

---

splunk_connect_for_snmp/snmp/manager.py

The original values could result in very large responses greater than MTU SNMP devices may not always be smart enough to downsize the response. This change will only collect the first repeater reducing total duplicates and will only ask for 10 vars per request similar to net-tools snmpbulkwalk command.

fix: Reduce requested vars per msg

---

charts/splunk-connect-for-snmp/Chart.lock
charts/splunk-connect-for-snmp/Chart.yaml
charts/splunk-connect-for-snmp/templates/inventory/job.yaml
charts/splunk-connect-for-snmp/templates/scheduler/deployment.yaml
charts/splunk-connect-for-snmp/templates/traps/deployment.yaml
charts/splunk-connect-for-snmp/templates/worker/deployment.yaml
splunk_connect_for_snmp/snmp/manager.py
splunk_connect_for_snmp/snmp/tasks.py

Using a new list provided by the mib library when a worker starts up re-load all standard mibs. While not all standard mibs will be required this should save a non-trival amount of time in the discovery phase.

feat: Load all standard mibs.

---

splunk_connect_for_snmp/snmp/manager.py

This change decrease walk time by 2 times. Instead of using retry variable after loading all of the missing mibs and going through all of the walk OIDs again, we repeat process_snmp_data right after loading mibs.
I ran it locally against 1.3.6.1.2.1 OID. Before the change walk took 20 minutes, after the change it was decreased to 10 minutes.

fix: repeat process_snmp_data right after loading mibs

---

splunk_connect_for_snmp/snmp/manager.py

Fix problem with empty string comparision. Because of previously added pre-commit, when all mibs are loaded, from self.is_mib_konwn "" is sometimes returned and breaks if condition:
```
if mib and mib not in remotemibs:
remotemibs.append(mib)
```
Unit tests and tested locally

fix: exclude empty string from remotemibs

---

charts/splunk-connect-for-snmp/templates/worker/deployment.yaml
charts/splunk-connect-for-snmp/values.yaml
docs/bestpractices.md
splunk_connect_for_snmp/snmp/manager.py
test/snmp/test_utils.py

This is a fix for an `OID not increasing` error returned from the SNMP device. This is being caused by wrong sequence of OIDs and is a problem on the device. This PR adds a way to ignore that problem via HELM configuration. 
Fixes # [(issue)](https://splunk.atlassian.net/browse/ADDON-47563)
I ran it locally and with Helm dry run. It will be tested on NOVA before merge with main.

fix: add ignoring increasing oids error for certain hosts

---

splunk_connect_for_snmp/snmp/manager.py
test/snmp/test_mibs.py

When mib loading fails we catch the exception instead propagating it higher and stopping whole process.
I wrote unit tests

fix: handle error during mib loading

---

charts/splunk-connect-for-snmp/templates/worker/deployment.yaml
integration_tests/test_poller_integration.py
splunk_connect_for_snmp/snmp/manager.py

This PR changes the default udpConnectionTimeout of SNMP operations to 3 seconds.

fix: change the default udpConnectionTimeout

---

integration_tests/test_poller_integration.py

This PR adds a mechanism of retrying splunk search in integration tests to avoid randomly failing CI pipelines.
N/A

test: add retry mechanism to splunk queries of integration tests

---

poetry.lock
pyproject.toml

This PR replaces celerybeatmongo repository. It contains PR fixing `can't compare offset-naive and offset-aware datetimes` error.
Integration tests

fix: replace celerybeatmongo repo 

---

docs/gettingstarted/mk8s/k8s-microk8s.md

This PR deletes redundant sudo commands for microk8s and change the way of enabling dns addon.
N/A
N/A

doc: get rid off redundant sudos

---

splunk_connect_for_snmp/snmp/manager.py
splunk_connect_for_snmp/snmp/tasks.py
test/snmp/test_get_varbinds.py

This PR changes the way small walk feature works. Doesn't make sense to traverse full tree with walk if customer knows from the very beginning what MIB families it he want to poll from.
Manual tests, unit tests

fix: disable first full walk when small walk is enabled

---

charts/splunk-connect-for-snmp/templates/worker/_helpers.tpl
charts/splunk-connect-for-snmp/templates/worker/poller/deployment.yaml
charts/splunk-connect-for-snmp/templates/worker/sender/deployment.yaml
charts/splunk-connect-for-snmp/templates/worker/trap/deployment.yaml
charts/splunk-connect-for-snmp/values.yaml
splunk_connect_for_snmp/snmp/tasks.py

This PR fixes shared concurrency  and prefetch values being used across every worker type (so all of them are recreated if the values changed for just one). Additionally, max walk retry difference can be configured from Helm.

fix: worker pods recreation

---

charts/splunk-connect-for-snmp/templates/common/scheduler-inventory.yaml
charts/splunk-connect-for-snmp/values.yaml

When no `poller.inventory` is specified, there is a problem with an infinite `ContainerCreating` state.
Manual and integration tests

fix: inventory csv pod container creating

---

.github/workflows/cd-pages.yaml

Mibserver dependency version is stuck on `1.14.2`.
N/A

fix: add helm repo update

---

.github/workflows/ci-main.yaml
charts/splunk-connect-for-snmp/templates/common/sim-secret.yaml
charts/splunk-connect-for-snmp/templates/sim/_helpers.tpl
charts/splunk-connect-for-snmp/templates/sim/deployment.yaml
charts/splunk-connect-for-snmp/values.yaml
docs/configuration/sim-configuration.md

This PR adds:
1. a way to use your own secret to log into the SignalFx
2. reloading pod when signalfxToken/signalfxRealm changes
Manual tests, integration tests

fix: add another way of mounting sim secrets

---

create_packages.sh

Get OTEL image from appVersion from Chart.yaml instead of from chart file name.
N?A
N/A

fix: otel image for chart appversion

---

docs/configuration/configuring-profiles.md
docs/gettingstarted/sc4snmp-installation.md
docs/offlineinstallation/offline-sc4snmp.md
docs/small-environment.md

Decrease the frequency of the default profiles to not to suggest querying all MIB families every 60 seconds.
N/A
N/A

doc: modify installation profile

---

charts/splunk-connect-for-snmp/templates/traps/service.yaml
docs/configuration/trap-configuration.md
splunk_connect_for_snmp/splunk/tasks.py

Add option to configure nodePort for traps service, what makes configuration of a multnode environment easier.
N/A

fix: add nodeport to trap service

---

charts/splunk-connect-for-snmp/templates/worker/_helpers.tpl

Fix helm issue when poller is empty in main values.yaml file:
```
executing "environmental-variables" at <.Values.poller.metricsIndexingEnabled>: nil pointer evaluating interface {}.metricsIndexingEnabled
```
N/A
N/A

fix: helm metrics indexing enabled issue

---

docs/gettingstarted/mk8s/k8s-microk8s.md

This PR adds a concrete version of microk8s to be installed, as from 1.26v one of the api that we still use in mibserver is deprecated. This hot fix will be deleted when the new version of the mibserver is ready.
Manual test.
N/A

doc: add channel to microk8s installation instruction

---

poetry.lock
pyproject.toml
splunk_connect_for_snmp/snmp/manager.py
splunk_connect_for_snmp/snmp/varbinds_resolver.py
test/snmp/test_do_work.py
test/snmp/test_get_varbinds.py
test/snmp/test_process_snmp_data.py
test/snmp/test_varbinds_resolver.py

This PR makes it possible to allow using compound indexes in SC4SNMP.
So far, there was only a way to specify one index in polling, like:
- ["IF-MIB", "ifInOctets", 1"]
Now, we can use complex indexes as well:
- ['IP-MIB', 'ipAddressStatus', 'ipv4', '172.31.27.144']
Manual tests, unit tests, integration tests

fix: refactor varBinds mechanism and implement compound indexes

---

CHANGELOG.md
splunk_connect_for_snmp/common/inventory_processor.py
test/common/test_inventory_processor.py

This change will fix skipping non existing group - instead we will treat this group automatically as a hostname.
Unit tests, manual tests

fix: treating not existing group name as a hostname

---

.github/dependabot.yml
poetry.lock

Bumps [pymdown-extensions](https://github.com/facelessuser/pymdown-extensions) from 9.5 to 10.0.
Added manually due to dependabot issues with rebasing to main branch.

ci: bump pymdown-extensions from 9.5 to 10.0 

---

.github/workflows/agreements.yaml
.github/workflows/release-notes.yaml

Add permissions for release notes preview after updating the workflow version to 1.3.4.
N/A
N/A

ci: add workflow permissions

---

CHANGELOG.md
splunk_connect_for_snmp/snmp/manager.py

Fix to issue with matching enterprise oid to first found vendor. If enterprise oid is part of path the search will end on checking for matching vendor.
manual test

fix: stop search for enterprise oid

---

CHANGELOG.md
charts/splunk-connect-for-snmp/templates/worker/_helpers.tpl
charts/splunk-connect-for-snmp/values.yaml
docs/bestpractices.md
docs/configuration/worker-configuration.md
rendered/manifests/tests/splunk-connect-for-snmp/templates/inventory/job.yaml
rendered/manifests/tests/splunk-connect-for-snmp/templates/worker/poller/deployment.yaml
rendered/manifests/tests/splunk-connect-for-snmp/templates/worker/sender/deployment.yaml
rendered/manifests/tests/splunk-connect-for-snmp/templates/worker/trap/deployment.yaml
rendered/manifests/tests_autoscaling_enabled/splunk-connect-for-snmp/templates/inventory/job.yaml
rendered/manifests/tests_autoscaling_enabled/splunk-connect-for-snmp/templates/worker/poller/deployment.yaml
rendered/manifests/tests_autoscaling_enabled/splunk-connect-for-snmp/templates/worker/sender/deployment.yaml
rendered/manifests/tests_autoscaling_enabled/splunk-connect-for-snmp/templates/worker/trap/deployment.yaml
rendered/manifests/tests_autoscaling_enabled_deprecated/splunk-connect-for-snmp/templates/inventory/job.yaml
rendered/manifests/tests_autoscaling_enabled_deprecated/splunk-connect-for-snmp/templates/worker/poller/deployment.yaml
rendered/manifests/tests_autoscaling_enabled_deprecated/splunk-connect-for-snmp/templates/worker/sender/deployment.yaml
rendered/manifests/tests_autoscaling_enabled_deprecated/splunk-connect-for-snmp/templates/worker/trap/deployment.yaml
rendered/manifests/tests_only_polling/splunk-connect-for-snmp/templates/inventory/job.yaml
rendered/manifests/tests_only_polling/splunk-connect-for-snmp/templates/worker/poller/deployment.yaml
rendered/manifests/tests_only_polling/splunk-connect-for-snmp/templates/worker/sender/deployment.yaml
rendered/manifests/tests_only_traps/splunk-connect-for-snmp/templates/worker/sender/deployment.yaml
rendered/manifests/tests_only_traps/splunk-connect-for-snmp/templates/worker/trap/deployment.yaml
rendered/manifests/tests_probes_enabled/splunk-connect-for-snmp/templates/inventory/job.yaml
rendered/manifests/tests_probes_enabled/splunk-connect-for-snmp/templates/worker/poller/deployment.yaml
rendered/manifests/tests_probes_enabled/splunk-connect-for-snmp/templates/worker/sender/deployment.yaml
rendered/manifests/tests_probes_enabled/splunk-connect-for-snmp/templates/worker/trap/deployment.yaml
splunk_connect_for_snmp/snmp/tasks.py

This PR is to make walk max retries configurable, as this is hardcoded to be 50 retries and it takes a lot of resources and time to walk devices that are unavailable.
Unit tests

fix: make walk max retries parameter configurable

---

.github/workflows/ci-release.yaml

Update semantic release to use splunk/semantic-release-action instead of cycjimmy//semantic-release-action.
N/A
N/A
N/A

fix: update semantic-relese

---

docs/bestpractices.md
splunk_connect_for_snmp/traps.py

This PR adds logging for snmp traps errors
Manual testing

fix: add logs in traps server for situations when incoming traps have wrong credentials

---

docs/bestpractices.md

fix formatting of Debug Splunk Connect for SNMP documentation

fix: fix formatting of Debug Splunk Connect for SNMP documentation

---

.github/workflows/ci-release.yaml

Update semantic-release-replace-plugin as @google/semantic-release-replace-plugin got depricated.

chore: fix semantic-release-replace-plugin

---

ui_tests/pages/profiles_page.py
ui_tests/tests/test_splunk_integration.py

This PR fixes log message in set_profile_name function in UI tests which was saying that the frequency is being changed. Also a sleep time is decreased in one UI test, because it caused the test to fail in some situations

Fix: fix UI tests

---

CHANGELOG.md
splunk_connect_for_snmp/snmp/auth.py
test/snmp/test_auth.py

Adds support for different security levels in snmpv3:
- NoAuthNoPriv
- AuthNoPriv
- AuthPriv
manual test, unit test

fix: add support for security level

---

CHANGELOG.md
charts/splunk-connect-for-snmp/templates/traps/deployment.yaml
charts/splunk-connect-for-snmp/templates/traps/service.yaml
charts/splunk-connect-for-snmp/values.schema.json
charts/splunk-connect-for-snmp/values.yaml
docs/configuration/trap-configuration.md
docs/configuration/values-params-description.md
docs/gettingstarted/enable-ipv6.md
docs/gettingstarted/mk8s/k8s-microk8s.md
mkdocs.yml
rendered/manifests/tests/splunk-connect-for-snmp/templates/traps/deployment.yaml
rendered/manifests/tests/splunk-connect-for-snmp/templates/traps/service.yaml
rendered/manifests/tests_autoscaling_enabled/splunk-connect-for-snmp/templates/traps/deployment.yaml
rendered/manifests/tests_autoscaling_enabled/splunk-connect-for-snmp/templates/traps/service.yaml
rendered/manifests/tests_autoscaling_enabled_deprecated/splunk-connect-for-snmp/templates/traps/deployment.yaml
rendered/manifests/tests_autoscaling_enabled_deprecated/splunk-connect-for-snmp/templates/traps/service.yaml
rendered/manifests/tests_enable_ui/splunk-connect-for-snmp/templates/traps/deployment.yaml
rendered/manifests/tests_enable_ui/splunk-connect-for-snmp/templates/traps/service.yaml
rendered/manifests/tests_only_traps/splunk-connect-for-snmp/templates/traps/deployment.yaml
rendered/manifests/tests_only_traps/splunk-connect-for-snmp/templates/traps/service.yaml
rendered/manifests/tests_probes_enabled/splunk-connect-for-snmp/templates/traps/deployment.yaml
rendered/manifests/tests_probes_enabled/splunk-connect-for-snmp/templates/traps/service.yaml
splunk_connect_for_snmp/common/inventory_processor.py
splunk_connect_for_snmp/snmp/auth.py
splunk_connect_for_snmp/snmp/manager.py
splunk_connect_for_snmp/traps.py
test/common/test_inventory_processor.py
test/inventory/test_loader.py
test/snmp/test_auth.py
test/snmp/test_do_work.py

Adds to SC4SNMP support for polling and receiving traps notifications from IPv6 devices.
unit, integration and manual tests

feat: support ipv6 for kubernetes

---

splunk_connect_for_snmp/common/collection_manager.py

Refactor of gather_elements() method.
manual, unit, integration

Fix: refactor gather elements

---

splunk_connect_for_snmp/splunk/tasks.py

Refactor of prepare method.
manual, integration, unit

fix: refactor prepare

---

sonar-project.properties
splunk_connect_for_snmp/inventory/tasks.py
ui_tests/config/config.py

Refactor of assign profile method. 
unit, integration, manual

Fix: assign profiles

---

splunk_connect_for_snmp/common/hummanbool.py
splunk_connect_for_snmp/inventory/tasks.py
test/common/test_humanbool.py
test/inventory/test_conditional_profiles.py

Refactor of create query
manual, unit, integration

fix: refactor create query

---

README.md
docs/microk8s/gui/enable-gui.md

disclaimer that UI not Splunk Supported

docs: disclaimer that UI not Splunk Supported

---

Dockerfile
entrypoint.sh

Migrate base docker image to Alpine for reduce CVEs:
Before: https://hub.docker.com/layers/library/python/3.10-bullseye/images/sha256-6aeb2ae527d111aabcfbc7340c70f2799371a3e6cbce136534153940b230cb79
After: https://hub.docker.com/layers/library/python/3.10-alpine3.21/images/sha256-2f8a694c5090bd071278f8280877d157fc766ef93abd3712d86390e0e298bf06
Biggest difference migration from Debian to Alpine, that alpine using `musl` instead of `glibc` that can give some side effects. By this reason I also tested it also manually
Runned whole test suite and run it locally

fix: migrate base image on alpine

---

integration_tests/test_poller_integration.py

Fix floating test, problem related with timeout, and it's failing only in k8s, but in docker not.
Run few times on  CI to be sure that it's not a luck

chore: fix floating timeout

---

CHANGELOG.md
charts/splunk-connect-for-snmp/templates/common/sim-secret.yaml

Issue:
This issue occurs when both .Values.secret.create and .[Values.secret.name](http://values.secret.name/) are set in the Helm values.
The problem arises because during the secret creation process, the value of .[Values.secret.name](http://values.secret.name/) is not being considered — the secret is created with a default name. However, when the deployment tries to reference the secret, it uses the name from .[Values.secret.name](http://values.secret.name/) (if it's set).
As a result, the deployment references a secret that doesn't exist, which leads to the pod failing to start with a CreateContainerConfigError.
To avoid this issue, we need to ensure that if .[Values.secret.name](http://values.secret.name/) is set, it's also used during secret creation.
Manual testing

fix: Fixed the sim pod creation issue when sim.secret.name was set

---

CHANGELOG.md
charts/splunk-connect-for-snmp/Chart.lock

In `1.15.20` version of the mibserver we changed the way templates are being rendered, we need to update the Chart.lock, as overriding image tag is not enough in this case.
Fixes # (issue) Linked to: https://github.com/splunk/splunk-connect-for-snmp/issues/1193
N/A

fix: update mibserver

---

integration_tests/automatic_setup_microk8s.sh

There was a new problem with integration tests pipeline:
```
Error: couldn't load repositories file (/home/runner/.config/helm/repositories.yaml): open /home/runner/.config/helm/repositories.yaml: permission denied
Installing SC4SNMP on Kubernetes
Error: INSTALLATION FAILED: An error occurred while checking for chart dependencies. You may need to run `helm dependency build` to fetch missing dependencies: found in Chart.yaml, but missing in charts/ directory: mongodb, redis, mibserver
```
Looks like we're missing sudo in `helm dep update` and the problem is related with that
integration tests
N/A

chore: add missing sudo

---

CHANGELOG.md
charts/splunk-connect-for-snmp/templates/worker/_helpers.tpl
charts/splunk-connect-for-snmp/values.schema.json
charts/splunk-connect-for-snmp/values.yaml
docs/microk8s/configuration/values-params-description.md
docs/microk8s/enable-ipv6.md
rendered/manifests/tests/splunk-connect-for-snmp/templates/worker/poller/deployment.yaml
rendered/manifests/tests_autoscaling_enabled/splunk-connect-for-snmp/templates/worker/poller/deployment.yaml
rendered/manifests/tests_autoscaling_enabled_deprecated/splunk-connect-for-snmp/templates/worker/poller/deployment.yaml
rendered/manifests/tests_enable_ui/splunk-connect-for-snmp/templates/worker/poller/deployment.yaml
rendered/manifests/tests_only_polling/splunk-connect-for-snmp/templates/worker/poller/deployment.yaml
rendered/manifests/tests_probes_enabled/splunk-connect-for-snmp/templates/worker/poller/deployment.yaml

Add flag `ipv6Enabled` to enable ipv6 polling for kubernetes deployment.
manual test

fix: add flag for ipv6 poller

---

integration_tests/automatic_setup_compose.sh
integration_tests/automatic_setup_microk8s.sh

There is an issue in integration tests, as running `splunk:latest` as we did before creates an infinite loop of `Waiting for Splunk`: https://github.com/splunk/splunk-connect-for-snmp/actions/runs/16875425784/job/47798790744?pr=1223
It is because the newest splunk image returns such a warning:
```
License not accepted, please adjust SPLUNK_GENERAL_TERMS and/or SPLUNK_START_ARGS to indicate you have accepted the current/latest version of the license.
The license you are accepting is the current/latest version of the Splunk General Terms, available here: https://www.splunk.com/en_us/legal/splunk-general-terms.html, as may be updated from time to time.
Unless you have jointly executed with Splunk a negotiated version of these General Terms that explicitly supersedes this agreement, by …
```

chore: fix license accept issue in integration tests 
